author_id = "lux"
app_id = "tpcat"
author_name = "Lux"
app_name = "Cat vs Toilet Paper"

[files]
_splash = { path = "assets/splash.png" }
bg = { path = "assets/bg.png" }
cat = { path = "assets/cat.png" }
done = { path = "assets/done.png" }
holder = { path = "assets/holder.png" }
holder2 = { path = "assets/holder2.png" }
paws = { path = "assets/paws.png" }
roll = { path = "assets/roll.png" }
stripe = { path = "assets/stripe.png" }
