author_id = "lux"
app_id = "tpcat"
author_name = "Lux"
app_name = "Cat vs Toilet Paper"

[files]
_splash = { path = "assets/splash.png" }
bg = { path = "assets/bg.png" }
cat = { path = "assets/cat.png" }
done = { path = "assets/done.png" }
holder = { path = "assets/holder.png" }

paws1 = { path = "assets/paws_1.png" }
paws2 = { path = "assets/paws_2.png" }
paws3 = { path = "assets/paws_3.png" }
paws4 = { path = "assets/paws_4.png" }

roll1 = { path = "assets/roll_1.png" }
roll2 = { path = "assets/roll_2.png" }
roll3 = { path = "assets/roll_3.png" }
roll4 = { path = "assets/roll_4.png" }
roll5 = { path = "assets/roll_5.png" }

stripe_1 = { path = "assets/stripe_1.png" }
stripe_2 = { path = "assets/stripe_2.png" }
stripe_3 = { path = "assets/stripe_3.png" }
